# Generated by Django 2.0.5 on 2018-05-11 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
                ('story', models.TextField(blank=True)),
                ('createdTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived', models.NullBooleanField(default=False)),
            ],
        ),
    ]
