# Generated by Django 2.0.5 on 2018-05-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='createdTime',
            new_name='date',
        ),
    ]
