# Generated by Django 2.0.5 on 2018-05-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180511_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=180),
        ),
    ]
