# Generated by Django 2.0.5 on 2018-06-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='hearts',
            field=models.IntegerField(default=0),
        ),
    ]
